name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/Transmitly.ChannelProvider.Twilio/**"
jobs:
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/.github/workflows/build-and-deploy-channel-provider-group.yml@main
    with: 
      channelProviderName: Transmitly.ChannelProvider.Twilio
    secrets: inherit
      
